name: Run Cypress Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # ou a versão que você está usando
      - name: Install dependencies
        run: |
          npm ci # ou `npm install` se você não estiver usando o `package-lock.json`
      - name: Install Cypress
        run: npm install cypress
      - name: Run Cypress tests
        run: npx cypress run
      - name: Upload Cypress test results (optional)
        uses: actions/upload-artifact@v3
        with:
          name: cypress-test-results
          path: cypress/results
